
services:
  - type: web
    name: holy-unblocker
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    repo: https://github.com/QuiteAFancyEmerald/Holy-Unblocker
